### PR TITLE
fix: skip OpenAI parameter filtering for custom providers

### LINKED ISSUE #1465: [Feature]: Custom providers should not use filterOpenAISpecificParameters
### Prerequisites

- [x] I have searched existing issues and discussions to avoid duplicates

### Problem to solve

Image
In the figure above, when reaching the default branch, all are custom providers. In this case, applying filterOpenAISpecificParameters seems inappropriate. For example, the Doubao model I use supports the "minimal" value for the Reasoning parameter.

### Proposed solution

Remove filterOpenAISpecificParameters

### Alternatives considered

_No response_

### Area(s)

Core (Go)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Radheshg04**
## Summary

Skip OpenAI parameter filtering for custom providers to allow passing all parameters without modification.

## Changes

- Added a check to determine if the provider is a custom provider (not in the `StandardProviders` list)
- When using a custom provider, the code now skips the `filterOpenAISpecificParameters()` function
- Updated changelog to document this fix

## Type of change

- [x] Bug fix
- [ ] Feature
- [ ] Refactor
- [ ] Documentation
- [ ] Chore/CI

## Affected areas

- [x] Core (Go)
- [ ] Transports (HTTP)
- [x] Providers/Integrations
- [ ] Plugins
- [ ] UI (Next.js)
- [ ] Docs

## How to test

Test with a custom provider that uses OpenAI-compatible API:

```sh
# Core/Transports
go version
go test ./...

# Test with a custom provider request that includes OpenAI-specific parameters
# Verify that parameters are not filtered out when using a custom provider
```

## Breaking changes

- [ ] Yes
- [x] No

## Related issues

Closes #1465

## Security considerations

No security implications as this change only affects parameter handling for API requests.

## Checklist

- [x] I read `docs/contributing/README.md` and followed the guidelines
- [x] I added/updated tests where appropriate
- [x] I updated documentation where needed
- [x] I verified builds succeed (Go and UI)
- [x] I verified the CI pipeline passes locally if applicable

### CODE REVIEW

**Comment by Radheshg04** [comment]
* **#1468** <a href="https://app.graphite.com/github/pr/maximhq/bifrost/1468?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/maximhq/bifrost/1468?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Pratham-Mishra04 — APPROVED** [review]

File: core/providers/openai/chat.go [hunk 1]
```diff
@@ -65,6 +66,11 @@ func ToOpenAIChatRequest(bifrostReq *schemas.BifrostChatRequest) *OpenAIChatRequ
 		}
 		return openaiReq
 	default:
+		// Check if provider is a custom provider
+		isCustomProvider := !slices.Contains(schemas.StandardProviders, bifrostReq.Provider)
```
Comment (akshaydeo) [inline core/providers/openai/chat.go]: @Radheshg04 I think the better approach here is

when we create BifrostContext - we can add IsCustomProvider key in it
and check it here

this way we can use the same check everywhere required

Comment (Radheshg04) [reply core/providers/openai/chat.go]: agreed, that is a much cleaner and scalable approach

File: core/bifrost.go [hunk 2]
```diff
@@ -2990,6 +2990,7 @@ func (bifrost *Bifrost) handleRequest(ctx *schemas.BifrostContext, req *schemas.
 		requestID := uuid.New().String()
 		ctx.SetValue(schemas.BifrostContextKeyRequestID, requestID)
 	}
+	ctx.SetValue(schemas.BifrostContextKeyIsCustomProvider, !IsStandardProvider(provider))
```
Comment (akshaydeo) [inline core/bifrost.go]: this is wrong place - cause after fallbacks the provider might change cc @Pratham-Mishra04

File: core/schemas/bifrost.go [hunk 3]
```diff
@@ -164,7 +164,8 @@ const (
 	BifrostContextKeyIsEnterprise                        BifrostContextKey = "is-enterprise"                                    // bool (set by bifrost - DO NOT SET THIS MANUALLY))
 	BifrostContextKeyAvailableProviders                  BifrostContextKey = "available-providers"                              // []ModelProvider (set by bifrost - DO NOT SET THIS MANUALLY))
 	BifrostContextKeyRawRequestResponseForLogging        BifrostContextKey = "bifrost-raw-request-response-for-logging"         // bool (set by bifrost - DO NOT SET THIS MANUALLY))
-	BifrostContextKeyRetryDBFetch                       BifrostContextKey = "bifrost-retry-db-fetch"                            // bool (set by bifrost - DO NOT SET THIS MANUALLY))
+	BifrostContextKeyRetryDBFetch                        BifrostContextKey = "bifrost-retry-db-fetch"                           // bool (set by bifrost - DO NOT SET THIS MANUALLY))
+	BifrostContextKeyIsCustomProvider                    BifrostContextKey = "bifrost-is-custom-provider"                       // bool (set by bifrost - DO NOT SET THIS MANUALLY))
```
[the remark this answers is not in the document]
Comment (Radheshg04) [reply core/schemas/bifrost.go:172]: adding xai to standard providers list

**Comment by akshaydeo** [comment]
### Merge activity

* **Jan 29, 12:23 PM UTC**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.com/github/pr/maximhq/bifrost/1468).
* **Jan 29, 12:24 PM UTC**: [Graphite](https://app.graphite.com/github/pr/maximhq/bifrost/1468) couldn't merge this PR because it had merge conflicts.
* **Jan 29, 12:36 PM UTC**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.com/github/pr/maximhq/bifrost/1468).
* **Jan 29, 12:37 PM UTC**: @akshaydeo merged this pull request with [Graphite](https://app.graphite.com/github/pr/maximhq/bifrost/1468).
