### PR TITLE
remove pricing warn logs, tool call in streaming log fixes and chores

### LINKED ISSUE #542: [Feature]: Logs should show timestamps is browser timezone
### Prerequisites

- [x] I have searched existing issues and discussions to avoid duplicates

### Problem to solve

The timestamps in the logs view should be in browser timezone, currently they are in UTC.

Better yet, if we can provide a timezone picker, it would be great.

Image

### Proposed solution

If we can provide a timezone picker, it would be great.

### Alternatives considered

_No response_

### Area(s)

UI (Next.js)

### Additional context

_No response_

### LINKED ISSUE #552: [Bug]: "index" not specified for tool calls in OpenAI chunks
### Prerequisites

- [x] I have searched existing issues and discussions to avoid duplicates
- [x] I am using the latest version (or have tested against main/nightly)

### Description

As the title states.

### Steps to reproduce

Do any tool call.

### Expected behavior

Tool calls have their index enumerated on their object.

### Actual behavior

They aren't.

### Affected area(s)

Core (Go)

### Version

All

### Environment

```text

```

### Relevant logs/output

```shell

```

### Regression?

_No response_

### Severity

Low (minor issue or cosmetic)

### LINKED ISSUE #565: The "pricing not found for model ..., skipping cost calculation" message is repeated for each request processed, which is too noisy for the warn level.
The "pricing not found for model ..., skipping cost calculation" message is repeated for each request processed, which is too noisy for the warn level.

Is it possible to change its log level to debug and only log a warning for each model at time of first use or if the last warn message was logged some time ago?

_Originally posted by @harry-xm in https://github.com/maximhq/bifrost/discussions/524_

### PR DESCRIPTION
**Pull request by akshaydeo**
## Summary

Changed pricing log level from WARN to DEBUG when pricing is not found for a model, and optimized the governance plugin check in the HTTP middleware.

## Changes

- Changed the log level from `WARN` to `DEBUG` in the pricing manager when pricing is not found for a model and provider, reducing log noise for expected scenarios. Closes #565
- Optimized the virtual key provider routing middleware by moving the governance plugin check outside the request handler function, improving performance by evaluating it only once at initialization
- Fix: fixes tool call accumulation in logs and index is now always visible for choices. fixes #552
- Fixes time representation on LogTable - now time is in local browser timezone (12 hrs). closes #542

## Type of change

- [x] Refactor
- [x] Bug fix

## Affected areas

- [x] Core (Go)
- [x] Transports (HTTP)
- [x] Plugins

## How to test

Verify that the pricing manager no longer logs warnings when pricing is not found:

```sh
# Core/Transports
go test ./framework/pricing/...
go test ./transports/bifrost-http/handlers/...
```

## Breaking changes

- [x] No

## Security considerations

No security implications as this only changes log levels and optimizes middleware initialization.

### CODE REVIEW

**Comment by akshaydeo** [comment]
* **#571** <a href="https://app.graphite.dev/github/pr/maximhq/bifrost/571?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/maximhq/bifrost/571?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: ui/app/logs/views/logDetailsSheet.tsx [hunk 1]
```diff
@@ -205,21 +205,6 @@ export function LogDetailSheet({ log, open, onOpenChange }: LogDetailSheetProps)
 						</>
 					)}
 				</div>
-				{toolChoice && (
```
Comment (Pratham-Mishra04) [inline ui/app/logs/views/logDetailsSheet.tsx:208]: any specific reason for removing this?

Comment (akshaydeo) [reply ui/app/logs/views/logDetailsSheet.tsx:208]: we already have it in params

Comment (Pratham-Mishra04) [reply ui/app/logs/views/logDetailsSheet.tsx:208]: okay

**Review by Pratham-Mishra04 — APPROVED** [review]

**Comment by akshaydeo** [comment]
### Merge activity

* **Oct 7, 9:37 AM UTC**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/maximhq/bifrost/571).
* **Oct 7, 9:37 AM UTC**: @akshaydeo merged this pull request with [Graphite](https://app.graphite.dev/github/pr/maximhq/bifrost/571).
