### PR TITLE
fix: mcp client header updates

### LINKED ISSUE #1560: PUT /api/mcp/client/{id} silently drops headers and auth_type fields
## Summary

The `PUT /api/mcp/client/{id}` endpoint returns `200 OK` with `"MCP client edited successfully"` but silently fails to persist the `headers` and `auth_type` fields in the database. Other fields in the same request (e.g. `name`, `is_ping_available`, `tool_sync_interval`) are saved correctly.

This also affects the MCP Config UI, which uses the PUT endpoint internally — header changes made through the dashboard are lost on save.

## Environment

- **Bifrost version:** v1.4.4
- **Deployment:** Docker (`maximhq/bifrost:v1.4.4`)
- **Database:** SQLite (default)

### 1. Create an MCP client with headers (works correctly)

```bash
TOKEN="<session-token>"

curl -X POST \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  "https://<bifrost>/api/mcp/client" \
  -d '{
    "name": "TestClient",
    "connection_type": "http",
    "connection_string": "https://example.com/mcp",
    "auth_type": "headers",
    "headers": {
      "Authorization": "Bearer my-secret-token"
    },
    "is_ping_available": false
  }'
```

**Result:** `headers` and `auth_type` are correctly stored in the database. ✅

### 2. Update the client via PUT (bug)

```bash
CLIENT_ID="<client_id from step 1>"

curl -X PUT \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  "https://<bifrost>/api/mcp/client/$CLIENT_ID" \
  -d '{
    "name": "TestClient",
    "connection_type": "http",
    "connection_string": "https://example.com/mcp",
    "auth_type": "none",
    "headers": {
      "Authorization": "Bearer new-token"
    },
    "is_ping_available": true
  }'
```

**Response:** `200 OK`
```json
{"message": "MCP client edited successfully", "status": "success"}
```

### 3. Verify database state

```sql
SELECT name, auth_type, headers_json, is_ping_available
FROM config_mcp_clients WHERE name = 'TestClient';
```

**Result:**
| name | auth_type | headers_json | is_ping_available |
|------|-----------|-------------|-------------------|
| TestClient | `headers` | `{}` | `1` |

## Expected Behavior

All fields in the PUT body should be persisted, including `headers` and `auth_type`.

| Field | Expected | Actual |
|-------|----------|--------|
| `name` | saved ✅ | saved ✅ |
| `is_ping_available` | saved ✅ | saved ✅ |
| `tool_sync_interval` | saved ✅ | saved ✅ |
| `connection_string` | saved ✅ | saved ✅ |
| **`headers`** | **saved** | **silently dropped** ❌ |
| **`auth_type`** | **saved** | **silently dropped** ❌ |

## Actual Behavior

- The PUT handler acknowledges the request with `200 OK` and a success message.
- `headers` and `auth_type` are silently ignored — the database retains their previous values.
- All other fields in the same request body are persisted correctly.

## Impact

- **UI is broken for header edits:** The MCP Config dashboard uses PUT internally, so any header changes made through the UI are lost on save. Users cannot add, modify, or remove authentication headers on existing MCP clients without a workaround.
- **Silent data loss:** The 200 response misleads both users and integrations into thinking the update succeeded.

## Workaround

Delete the MCP client and recreate it via `POST /api/mcp/client`, which correctly persists all fields including `headers` and `auth_type`.

```bash
# Delete
curl -X DELETE -H "Authorization: Bearer $TOKEN" \
  "https://<bifrost>/api/mcp/client/$CLIENT_ID"

# Recreate with updated headers
curl -X POST -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  "https://<bifrost>/api/mcp/client" \
  -d '{ "name": "TestClient", ... }'
```

**Note:** After delete + create, Bifrost may return a 500 error (`"Added to core but failed to create MCP config in database"`) due to a stale in-memory reference. The database entry is created correctly despite the error. A container restart resolves the inconsistency between in-memory state and database.

### PR DESCRIPTION
**Pull request by Radheshg04**
## Summary

Fix MCP client update functionality to properly handle existing configuration values when updating clients.

## Changes

- Fixed the MCP client update handler to preserve existing configuration values when not explicitly provided in the update request
- Added logic to update the in-memory MCP client configuration after a successful database update
- Improved header handling during updates to properly merge incoming headers with existing ones
- Fixed UI handling of `tool_sync_interval` to default to 0 when the value is null

## Type of change

- [x] Bug fix
- [ ] Feature
- [ ] Refactor
- [ ] Documentation
- [ ] Chore/CI

## Affected areas

- [x] Core (Go)
- [x] Transports (HTTP)
- [ ] Providers/Integrations
- [ ] Plugins
- [x] UI (Next.js)
- [ ] Docs

## How to test

1. Create an MCP client with connection settings, headers, and auth configuration
2. Edit the client and update only some fields (like name or tools)
3. Verify that the unmodified fields (connection string, auth settings) are preserved
4. Verify that headers are properly merged when updating

```sh
# Core/Transports
go test ./transports/bifrost-http/handlers/...

# UI
cd ui
pnpm i
pnpm test
```

## Breaking changes

- [ ] Yes
- [x] No

## Related issues

Closes #1560.

## Security considerations

This change ensures sensitive configuration values like connection strings and OAuth credentials are properly preserved during updates.

## Checklist

- [x] I added/updated tests where appropriate
- [x] I verified builds succeed (Go and UI)
- [x] I verified the CI pipeline passes locally if applicable

### CODE REVIEW

**Comment by Radheshg04** [comment]
* **#1572** <a href="https://app.graphite.com/github/pr/maximhq/bifrost/1572?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/maximhq/bifrost/1572?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: transports/bifrost-http/handlers/mcp.go [hunk 1]
```diff
@@ -409,23 +409,30 @@ func (h *MCPHandler) updateMCPClient(ctx *fasthttp.RequestCtx) {
 
 	}
 	// Convert to schemas.MCPClientConfig for runtime bifrost client (without tool_pricing)
-	// Dereference IsPingAvailable pointer, defaulting to true if nil
 	isPingAvailable := true
 	if req.IsPingAvailable != nil {
 		isPingAvailable = *req.IsPingAvailable
 	}
+	connectionType := existingConfig.ConnectionType
+	if req.ConnectionType != "" {
```
Comment (Pratham-Mishra04) [inline transports/bifrost-http/handlers/mcp.go]: cannot change connection type as well

File: transports/bifrost-http/handlers/mcp.go [hunk 2]
```diff
@@ -585,24 +602,25 @@ func mergeMCPRedactedValues(incoming *configstoreTables.TableMCPClient, oldRaw,
...
+							continue
+						}
 					}
-					continue
 				}
 			}
-			// New header or changed header
 			merged.Headers[key] = incomingValue
 		}
+	} else if oldRaw.Headers != nil {
```
Comment (Pratham-Mishra04) [inline transports/bifrost-http/handlers/mcp.go:605]: but this will not let me remove all headers right?

File: transports/bifrost-http/handlers/mcp.go [hunk 3]
```diff
@@ -436,6 +443,16 @@ func (h *MCPHandler) updateMCPClient(ctx *fasthttp.RequestCtx) {
 		SendError(ctx, fasthttp.StatusInternalServerError, fmt.Sprintf("failed to update mcp client: %v please restart bifrost to keep core and database in sync", err))
 		return
 	}
+
+	if h.store.MCPConfig != nil {
```
Comment (Pratham-Mishra04) [inline transports/bifrost-http/handlers/mcp.go]: move this to UpdateMCPClient() in lib/config.go

File: transports/bifrost-http/handlers/mcp.go (hunk 2 above)
Comment (Radheshg04) [reply transports/bifrost-http/handlers/mcp.go:605]: yes, this change persists headers ,previously headers were being discarded

File: transports/bifrost-http/handlers/mcp.go (hunk 1 above)
Comment (Radheshg04) [reply transports/bifrost-http/handlers/mcp.go]: ok reverting this and auth type

File: transports/bifrost-http/handlers/mcp.go (hunk 2 above)
Comment (Pratham-Mishra04) [reply transports/bifrost-http/handlers/mcp.go:605]: no i mean if you remove all headers in your headers, will it allow that?

Comment (Radheshg04) [reply transports/bifrost-http/handlers/mcp.go:605]: yes

**Review by Pratham-Mishra04 — APPROVED** [review]

**Comment by Pratham-Mishra04** [comment]
### Merge activity

* **Feb 6, 6:42 PM UTC**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.com/github/pr/maximhq/bifrost/1572).
* **Feb 6, 6:43 PM UTC**: @Pratham-Mishra04 merged this pull request with [Graphite](https://app.graphite.com/github/pr/maximhq/bifrost/1572).
