### PR TITLE
fix: preserve explicit empty tool parameter schemas for openai paths

### LINKED ISSUE #2398: [Bug]: Bifrost automatically convert empty tool parameters (openai)
### Prerequisites

- [x] I have searched existing issues and discussions to avoid duplicates
- [x] I am using the latest version (or have tested against main/nightly)

### Description

currently, bifrost automatically convert empty tool parameter `parameters: {}` to `paramters: {type:"",properties:{}}`
This cause github copilot upstream provider error. I didn't test with other provider yet.
```
{
	"is_bifrost_error": false,
	"status_code": 400,
	"error": {
		"code": "invalid_request_body",
		"message": "Invalid schema for function 'get_search_view_results': '' is not valid under any of the given schemas."
	},
	"extra_fields": {
		"provider": "copilot-oai",
		"model_requested": "gpt-5-mini",
		"request_type": "responses_stream"
	}
}
```

Image

### Steps to reproduce

1. Add github copilot as upstream (api.business.githubcopilot.com, authorization tid=.. for debug) 
2. Send request to bifrost /v1/responses endpoint that have below tool definition
```
"tools": [
		{
			"name": "get_search_view_results",
			"description": "The results from the search view",
			"parameters": {},
			"type": "function",
			"strict": false
		}
	]
```
3. copilot response with  nvalid schema for function

### Expected behavior

Should not convert empty tool parameters definition

### Actual behavior

Tool parameters definition is conveted to empty type+proprties set

### Affected area(s)

Transports (HTTP)

### Version

1.4.18

### Environment

```text

```

### Relevant logs/output

```shell

```

### Regression?

_No response_

### Severity

Medium (some functionality impaired)

### PR DESCRIPTION
**Pull request by jerkeyray**
## Summary

Preserves explicit empty object schemas (`{}`) in tool function parameters while maintaining proper JSON Schema normalization for populated schemas.

Fixes a bug where `"parameters": {}` was being incorrectly rewritten into an invalid OpenAI function schema shape (`{"type":"","properties":{}}`). Now preserves `{}` as-is while keeping populated schemas like `{"type":"object","properties":{}}` unchanged.

## Changes

- Added `explicitEmptyObject` field to `ToolFunctionParameters` to track when a client provides a raw `{}` schema
- Modified `MarshalJSON` to preserve empty objects as `{}` instead of expanding them to `{"type":"","properties":{}}`
- Added `hasDefinedSchemaFields()` method to distinguish between explicit empty objects and populated schemas
- Updated `DeepCopyChatTool` to preserve the `explicitEmptyObject` flag during copying
- Added comprehensive tests for both chat and responses API paths to verify empty parameter preservation

## Type of change

- [x] Bug fix
- [ ] Feature
- [ ] Refactor
- [ ] Documentation
- [ ] Chore/CI

## Affected areas

- [x] Core (Go)
- [ ] Transports (HTTP)
- [x] Providers/Integrations
- [ ] Plugins
- [ ] UI (Next.js)
- [ ] Docs

## How to test

Verify that tool function parameters handle both empty and populated schemas correctly:

```bash
# Core/Transports
go test ./core/providers/openai/... -run TestToOpenAIChatRequest_PreservesExplicitEmptyToolParameters
go test ./core/providers/openai/... -run TestToOpenAIResponsesRequest_PreservesExplicitEmptyToolParameters
go test ./core/schemas/... -run TestToolFunctionParameters_ExplicitEmptyObjectPreserved

```

Test cases verify:

- Raw `{}` schemas remain as `{}`
- Populated schemas like `{"type":"object","properties":{}}` preserve their structure
- Normalization works correctly for both cases

## Screenshots/Recordings

N/A

## Breaking changes

- [ ] Yes
- [x] No

## Related issues

Closes #2398

## Security considerations

No security implications — this change only affects JSON serialization behavior for tool schemas.

## Checklist

- [x] I read `docs/contributing/README.md` and followed the guidelines
- [x] I added/updated tests where appropriate
- [ ] I updated documentation where needed
- [x] I verified builds succeed (Go and UI)
- [ ] I verified the CI pipeline passes locally if applicable

### CODE REVIEW

**Comment by jerkeyray** [comment]
* **#2463** <a href="https://app.graphite.com/github/pr/maximhq/bifrost/2463?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/maximhq/bifrost/2463?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: core/schemas/chatcompletions.go [hunk 1]
```diff
@@ -405,6 +409,8 @@ func (t *ToolFunctionParameters) UnmarshalJSON(data []byte) error {
 		t.AdditionalProperties = nil
 	}
 
+	var rawObject map[string]interface{}
+	t.explicitEmptyObject = Unmarshal(data, &rawObject) == nil && len(rawObject) == 0
```
Comment (akshaydeo) [inline core/schemas/chatcompletions.go]: do we really need to unmarshal here? 

we can use some byte checks to see if its empty - if is empty is the check we want to make

Comment (jerkeyray) [reply core/schemas/chatcompletions.go]: yes, removed the unmarshal here and replaced it with a simple byte check.
