### PR TITLE
review fixes

### LINKED ISSUE #1306: [Bug]: price precision for /v1/models
### Prerequisites

- [x] I have searched existing issues and discussions to avoid duplicates
- [x] I am using the latest version (or have tested against main/nightly)

### Description

the /v1/models API endpoint exposes pricing with reduced precision due to the %f string formatting, which defaults to 6 decimal places. 
Q: The 6 decimal for pricing per token is designed or a bug? This make the low costed models like grok-4-1-fast for example 2e-7 becoming zero cost in the /v1/models endpoint
```
{"id":"xai/grok-4-1-fast-reasoning","created":1763510400,"pricing":{"prompt":"0.000000","completion":"0.000000","input_cache_read":"0.000000"},"owned_by":"xai"}
```

### Steps to reproduce

1. docker image latest
2. config the xai
3. query the /v1/models

### Expected behavior

expect the precision to be 8 decimal or more

### Actual behavior

cut off to zero because of %f default 6 decimal

### Affected area(s)

Framework

### Version

v1.4.0-prerelease9

### Environment

```text
- macos
- docker
```

### Relevant logs/output

```shell

```

### Regression?

_No response_

### Severity

Low (minor issue or cosmetic)

### PR DESCRIPTION
**Pull request by akshaydeo**
## Summary

This PR fixes several type safety issues in provider implementations, improves error handling, and enhances stream accumulator thread safety to prevent race conditions.

## Fixes

Closes #1306

## Changes

- Added proper type safety checks for Gemini provider's safety settings, labels, and request metadata
- Fixed empty string check for Anthropic instructions parameter
- Added mutex locks to stream accumulator methods to prevent race conditions
- Improved deferred span cleanup to ensure proper resource release even during panics
- Enhanced string map extraction with a new utility function `SafeExtractStringMap`
- Updated file base64 test to use scenario-specific retry configuration
- Fixed Gemini speech handler to safely check for nil params
- Added proper cleanup for deferred spans and stream accumulators

## Type of change

- [x] Bug fix
- [ ] Feature
- [x] Refactor
- [ ] Documentation
- [ ] Chore/CI

## Affected areas

- [x] Core (Go)
- [ ] Transports (HTTP)
- [x] Providers/Integrations
- [x] Plugins
- [ ] UI (Next.js)
- [ ] Docs

## How to test

```sh
# Core/Transports
go version
go test ./...

# Test specific providers
go test ./core/providers/gemini/...
go test ./core/providers/anthropic/...
go test ./core/providers/bedrock/...

# Test streaming functionality
go test ./framework/streaming/...
```

## Breaking changes

- [ ] Yes
- [x] No

## Related issues

Fixes type safety issues and race conditions in stream processing.

## Security considerations

Improves type safety which helps prevent potential security issues from unexpected data types.

## Checklist

- [x] I added/updated tests where appropriate
- [x] I verified builds succeed (Go and UI)
- [x] I verified the CI pipeline passes locally if applicable

### CODE REVIEW

**Comment by akshaydeo** [comment]
* **#1309** <a href="https://app.graphite.com/github/pr/maximhq/bifrost/1309?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/maximhq/bifrost/1309?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `v1.4.0`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: core/providers/utils/utils.go [hunk 1]
```diff
@@ -1560,6 +1560,10 @@ func completeDeferredSpan(ctx *schemas.BifrostContext, result *schemas.BifrostRe
 		return
 	}
 
+	// Ensure cleanup executes even if downstream code panics
+	defer tracer.ClearDeferredSpan(traceID)
+	defer tracer.CleanupStreamAccumulator(traceID)
```
Comment (Pratham-Mishra04) [inline core/providers/utils/utils.go]: not have enough context around this change but this would decrement the reference counter - which ideally should happen only by plugins because plugins are referencing it

Comment (akshaydeo) [reply core/providers/utils/utils.go]: aah kay - actually forgot asking you reverting this
